### ISSUE TITLE
Support single colons

### ISSUE THREAD

**Issue by tancredi** [nonamenix/babel-vue-extractor#17]
Hi there,

Thanks for supporting v-* and :* attributes - this is great! Just one question: it seems to only pick up double quotes (E.g. `:foo-bar="gettext('bar-foo')"` will work but `:foo-bar='gettext("bar-foo")'` won't) - is there a particular reason for this? Would it be trivial to support?

**Comment by nonamenix** [comment]
@ykshatroff many thanks ) 

@tancredi https://pypi.python.org/pypi/babel-vue-extractor/1.4.2
